# Generated by Django 4.2.13 on 2024-06-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockcity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Date',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Description',
        ),
    ]
